on:
  pull_request:
    branches:
      - main
    types:
      - closed

# Later, in the jobs section of your actions.yml file.
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: mini-pc ssh connect
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.MINI_HOST }}
        username: ${{ secrets.MINI_USERNAME }}
        key: ${{ secrets.MINI_PRIVATE_KEY }}
        port: ${{ secrets.MINI_SSH_PORT }}
        script: |
          cd ~
          echo "hello"
